export const dummyData = [
  {
    id:"1",
    state_id: "S001",
    dist_id: "D001",
    block_id: "T001",
    gp_id: "G001",
    gp_name: "Kainda",
    youngFellowName: "John Doe",
    dateOfJoining: "01/01/2000",
    dateOfSubmission: "01/01/2023",
    achievement: "Achievement One",
    achievementPhoto: null,
    failure: "Failure One",
    planOfAction: "Plan of Action One",
  },
  {
    id:"2",
    state_id: "S002",
    dist_id: "D002",
    block_id: "T002",
    gp_name: "Kainda",
    gp_id: "G002",
    youngFellowName: "Jane Smith",
    dateOfJoining: "01/01/2001",
    dateOfSubmission: "01/01/2023",
    achievement: "Achievement Two",
    achievementPhoto: null,
    failure: "Failure Two",
    planOfAction: "Plan of Action Two",
  },
];
