name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Step 3: Deploy using SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment"

            # Navigate to project directory
            cd /home/ubuntu/NIRD

            # Pull latest code
            git pull origin main

            # Frontend: Install dependencies, build, and copy files
            cd frontend
            npm install
            npm run build
            sudo cp -R dist/ /var/www/vhosts/frontend/

            # Backend: Install dependencies, build, and restart server
            cd ../Backend
            npm install
            npm run build
            pm2 restart default

            echo "Deployment completed successfully"
