name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets '[{"Key":"tag:Name","Values":["<EC2_INSTANCE_TAG_NAME>"]}]' \
            --comment "Deploying website" \
            --parameters '{"commands":["
              set -e
              
              # Navigate to the website directory and pull the latest changes
              cd /home/ubuntu/NIRD
              git pull origin main

              # Frontend: Install dependencies, build, and copy to web root
              cd frontend
              npm install
              npm run build
              sudo cp -R dist/ /var/www/vhosts/frontend/

              # Backend: Install dependencies, build, and restart the server
              cd ../Backend
              npm install
              pm2 restart default
            "]}' \
            --timeout-seconds 600 \
            --output text
